-------- Generic
---@alias ItemLink string

--------- Texture
---@class TextureData
---@field texture string
---@field size [number, number]
---@field coords [number, number, number, number]

--------- Database
---@class Character
---@field name string
---@field race number
---@field className number
---@field group number
---@field cooldownGroup table<string, CurrentCooldown[]>

---@class Option
---@field categoryID number

-------- Preset
---@class MailPreset
---@field id? number
---@field name string
---@field to string
---@field color colorRGBA
---@field itemGroups table<string, boolean>
---@field custom ItemLink[]
---@field exclusion ItemLink[]

---@class ItemGroupOption
---@field label string
---@field CheckItemBelongsToGroup fun(itemLink: ItemLink): boolean
---@field IsEnabledInThisExpansion? fun(): boolean

------- Options
---@class OptionsCreateList
---@field GetText? fun(rowData): string
---@field SortComparator fun(a: any, b: any): boolean
---@field CustomizeRow? fun(frame: table, rowData: any, helpers)
---@field showCheckbox? boolean
---@field showRemoveIcon? boolean
---@field OnRemove? fun(rowData, OptionsCreateList): boolean
---@field hasHyperlink? boolean
---@field GetHyperlink? fun(rowData: any): string

------- AutoBuy
---@class AutoBuyItem
---@field itemLink ItemLink
---@field quantity number
---@field scope EAutoBuyScope
---@field scopeValue? string

------- MouseRing
---@class MouseRingData
---@field enabled boolean
---@field size number
---@field shape string
---@field colorR number
---@field colorG number
---@field colorB number
---@field useClassColor boolean
---@field hideBackground boolean
---@field showOutOfCombat boolean
---@field hideOnRightClick boolean
-- Cast swipe
---@field castSwipeEnabled boolean
---@field castSwipeR? number
---@field castSwipeG? number
---@field castSwipeB? number
---@field castSwipeUseClassColor boolean
-- GCD swipe
---@field gcdEnabled boolean
---@field gcdR? number
---@field gcdG? number
---@field gcdB? number
---@field gcdUseClassColor boolean
-- Trail
---@field trailEnabled boolean
---@field trailR? number
---@field trailG? number
---@field trailB? number
---@field trailUseClassColor boolean
---@field trailDuration number
